<div id="view-content">
	
<?php
// Artikeldaten anordnen und anzeigen
$data_object = $this->dbdata;

$art_name = $data_object->getModel ();
$art_dim = $data_object->getSpeicherinhalt ();
$art_weight = $data_object->getleergewicht ();
$art_pressure = $data_object->getBetriebsdruck ();
$art_temp = $data_object->getTemperaturMax ();
$art_loc = $data_object->getEinsatzgebiet ();

	
echo '<h1>Pufferspeicher ' . $art_name . '</h1>';
echo '<br>';
echo '<h3>Fassungsverm&ouml;gen:</h3>';
echo $art_dim . ' Liter';
echo '<br>';
echo '<h3>Betriebsdruck:</h3>';
echo $art_pressure.' bar';
echo '<br>';
echo '<h3>Brenntemperatur:</h3>';
echo $art_temp.' &deg;C';
echo '<br>';
echo '<h3>Leergewicht:</h3>';
echo $art_weight . 'Kg';
echo '<br>';
if (!is_array ( $art_loc )) {
	echo '<h3>Einsatzgebiete:</h3>';
	echo $art_loc->getEinsatzgebiet();
} else {
	echo '<h3>Einsatzgebiet:</h3>';
	foreach ( $art_loc as $each )
		echo $each->getEinsatzgebiet();
}
?>
</div>