<br /><br />
<div id="view-content">
// <?php
// echo "Einzelne Zeile per getBenutzer abrufen:<br>";
// echo $this->mustermann->getAnrede() ." ". $this->mustermann->getVorname() ." ". $this->mustermann->getNachname() ." ". "<br>".$this->mustermann->getEmail();
// ?>
<!-- <br><br><br> -->
// <?php 
// echo "Alle Benutzer per fetchAll abrufen:<br>";
// foreach($this->mustermaenner as $mustermann){
// echo $mustermann->getAnrede() ." ". $mustermann->getVorname() ." ". $mustermann->getNachname() ." ". "<br>".$mustermann->getEmail() . "<br><br>";
// }
// ?>


// <?php 
// $benutzerMapper = new Application_Model_BenutzerMapper();

// $test = $benutzerMapper->getBenutzer("test@test.de");
// $test->setPasswort("geheim");
// $benutzerMapper->updateBenutzer($test);


// // $test->setPasswort("maeh");
// // $test->setAnrede("Herr");



// // $benutzerMapper->updateBenutzer($test);

// //Benutzer einfügen

// // $testbenutzer = new Application_Model_Benutzer();
// // $testbenutzer->setAnrede("Frau");
// // $testbenutzer->setBerechtigung("Benutzer");
// // $testbenutzer->setNachname("Maier");
// // $testbenutzer->setVorname("Bob");
// // $testbenutzer->setPasswort("blub123");

// // $benutzerMapper->insertBenutzer($testbenutzer, "bob.maier2@email.de");

// //$benutzerMapper->deleteBenutzer($testbenutzer);

// if($benutzerMapper->existEmail("test@test.de")){
// 	echo "<br>email existiert<br>";
// }
// else{
// 	echo "<br>email existiert nicht<br>";
// }

// //Wärmetauscher Tests:

// $waermetauscher = new Application_Model_Waermetauscher();

// $waermetauscher->setModel("test");

// echo $waermetauscher->getModel();
echo '<br><br><br>';
echo '-------------------------------------------------------------------------------------';
 $waermetauschermapper = new Application_Model_WaermetauscherMapper();
 $bhd21 = $waermetauschermapper->getWaermetauscherByModel("BHD21");
 if(!($bhd21 = $waermetauschermapper->getWaermetauscherByModel("BHD21")))
 	echo "bhd21 anfrage fehlgeschlagen";
 else
 echo '<br>'.$bhd21->getStutzenmaterial();

 $blub = $bhd21->getWaermetauscherUnterkategorie();
// foreach($blub as $key){
// echo "<br>blub<br>";
// }
 echo "<br>".$blub[1]->getLaenge();
 
 $bla = $bhd21->getWaermetauscherEinsatzgebiet();
 
 echo "<br>".$bla[0]->getEinsatzgebiet();


// //$linkMapper = new Application_Model_LinkMapper();

// // $fall = $linkMapper->getLinkByHexaString("asdfasdfsd54f4sdaf564sd6f");

// // echo $fall['0']->getHexaString();

// // echo $fall['0']->getEmail();

 $benutzerMapper = new Application_Model_BenutzerMapper();

 $test = $benutzerMapper->getBenutzer("test@test.de");
 echo $test->getPasswort();
 
 echo "<br>";
 $wtmapper = new Application_Model_WaermetauscherMapper();
 
 $wtmapper->setTemperaturMax(200);
 $wtmapper->setTemperaturMin(100);
 $wtmapper->setEinsatzgebiet('Umrüstung von PKW`s auf Rapsöl');
 $wtmapper->setAnschluss(array('3/8" IG', '1/2" AG', '3/4" AG'));
 $wtmapper->setHoeheMax(450);
 $wtmapper->setHoeheMin(100);
// $wtmapper->setBreiteMax(150);
// $wtmapper->setBreiteMin(10);
  $produkt = $wtmapper->getWaermetauscher();
  
  echo '<br><br><br>';
  echo '-------------------------------------------------------------------------------------<br>';
  foreach($produkt as $key => $value){
	echo $value->getModel().'<br>';

}	
//  if($produkt != ""){
//  	foreach($produkt as $key => $value){
// 		echo $value->getModel().'<br>';
// 		echo $value->getTemperatur().'<br>';
// 	}
//  }
 
//
 echo '<br>-------------------------------------------------------------------------------------';
 echo '<br><br><br>';
 
 
 
 ?>



<!-- </div> -->
