<body>
<p>Hallo <?php echo $this->name; ?>,<br>
für Ihr Therminox-Konto wurde die Zurücksetzung des Passworts angefordert.
<br>
Wenn Sie dies nicht veranlasst haben, können Sie diese E-mail ignorieren.</p>

Mit dem folgenden Link wird Ihr Passwort zurückgesetzt.
<a href="therminox.local/account/recover/key/<?php echo $this->key?>">Passwort zurücksetzen</a>

<p>
Vielen Dank,<br>
Das Therminox Team
</p>
</body>