<body>
<p>Hallo <?php echo $this->name; ?>,<br>
Ihr Therminox-Account wurde erfolgreich erstellt.
<br>
Um die Registrierung abzuschließen, bestätigen Sie bitte Ihre E-mail Adresse, indem Sie auf den folgenden Link klicken:</p>

<a href="therminox.local/account/confirm/key/<?php echo $this->key?>">E-mail bestätigen</a>

<p>Nachdem du deine E-mail Adresse bestätigt hast, kannst du dich bei Therminox einloggen.
<br>
Vielen Dank,<br>
Das Therminox Team
</p>
</body>