<?php $this->headTitle()->append('Anmelden'); ?>
<?php $this->headLink()->appendStylesheet('/_files/css/login.css');?>
<div id="login_wrapper">
<h3>Anmelden</h3>
<?php echo $this->Errors($this->errorMessage)?>
<?php echo $this->form ?>
<div id="register"><p>Noch nicht registriert? <a href="/account/register">Jetzt registrieren!</a></p></div>
<div id="lost"><p>Passwort vergessen? <a href="/account/lost">Passwort zurücksetzen!</a></p></div>
</div>