<?php $this->headTitle()->append('Profil'); ?>
<?php $this->headLink()->appendStylesheet('/_files/css/login.css');?>
<div id="profile_wrapper">
<h3>Mein Profil</h3>
	<p>E-Mail: <?php echo $this->email?></p> 
	<?php echo $this->form; ?>
	<?php echo '<p>' . $this->success . '</p>';?>
	<a href="/account/password/">Passwort ändern</a>
	<br>
	<a href="/account/address/">Addressen verwalten</a>
	<br>
	<a href="/account/delete/">Account löschen</a>
</div>