<form id="<?php echo $this->element->getAttrib('id') ?>" action="<?php echo $this->element->getAction(); ?>"
				 method="<?php echo $this->element->getMethod(); ?>">
<p>
<?php echo $this->element->email; ?>
</p>
<p>
<?php echo $this->element->password; ?>
</p>
<p>
<?php echo $this->element->confirm_password; ?>
</p>
<p>
<?php echo $this->element->title; ?>
</p>
<p>
<?php echo $this->element->name; ?>
</p>
<p>
<?php echo $this->element->lastname; ?>
</p>
<?php echo $this->element->submit; ?>
</form>