<?php 
/*****************************************************************************
 * 											 								**
 * Allgemeine Infos:														**
 * Höhe: 150px 																**
 * Breite: dynamisch (848px jedoch nicht übersteigen, für 1024 Auflösung)	**
 * 																			**
 *****************************************************************************/
?>
<div id = "bannerImage"></div>
<div id ="bannerImageWiederholung"></div>

