<?php echo $this->doctype() ?>
<html>
	<head>
		<?php echo $this->jQuery(); 
			  echo $this->headTitle();
			  echo $this->headMeta();
			  echo $this->headStyle();
			  echo $this->headLink();
			  echo $this->headScript(); ?>
	</head>
	<body>
	<div id ="banner"><?php echo $this->render('banner.phtml');?>
		<div id = "account"><?php echo $this->render('account.phtml');?></div>
	</div>
	<div id = "menu"><?php echo $this->render('menu.phtml');?></div>
	<div id = "admin_letzteProdukte"><?php echo $this->render('admin_letzeProdukte.phtml');?></div>
	<div id = "inhalt">
	<?php echo $this->layout()->content; ?>
	</div>
	</body>
</html>
