<?php echo $this->doctype() . "\n"; ?>
<html lang="de">
	<head>
		<?php echo $this->jQuery(); 
			  echo $this->headTitle();
			  echo $this->headMeta();
			  echo $this->headStyle();
			  echo $this->headLink();
			  echo $this->headScript(); ?>
	</head>
	<body>
		<div id ="wrapper">
						<?php if ( count($this->messages) > 0 ) { //Flashmessenger will probably need its own div in the layout
					printf("<div id='flash'>%s</div>", $this->messages[0]); 
				}?>
				<div id ="banner"><?php echo $this->render('banner.phtml');?>
						<div id = "account"><?php echo $this->render('account.phtml');?></div>
				</div>
				<div id = "menu"><?php echo $this->render('menu.phtml');?></div>
				<div id = "admin_letzteProdukte"><?php echo $this->render('admin_letzteProdukte.phtml');?></div>
				<div id = "inhalt">
						<?php echo $this->layout()->content; ?>
				</div>	
				<div id = "fusszeile">
						<?php echo $this->render('fusszeile.phtml')?>
				</div>
		</div>
	</body>
</html>
