<?php echo $this->doctype() . "\n"; ?>
<html lang="de">
	<head>
		<?php echo $this->jQuery(); 
			  echo $this->headTitle();
			  echo $this->headMeta();
			  echo $this->headStyle();
			  echo $this->headLink();
			  echo $this->headScript(); ?>
	</head>
	<body>
		<div id ="wrapper">
				<div id = "content">
						<?php if ( count($this->messages) > 0 ) { //Flashmessenger will probably need its own div in the layout
							printf("<div id='flash'>%s</div>", $this->messages[0]); 
						}?>
						<div id ="banner">
								<div id = "account"><?php echo $this->render('_layout/account.phtml');?></div>
								<?php echo $this->render('_layout/banner.phtml');?>
						</div>
						<div id = "menu"><?php echo $this->render('_layout/menu.phtml');?></div>
						<div id = "admin_letzteProdukte"><?php echo $this->render('_layout/admin_letzteProdukte.phtml');?></div>
						<div id = "inhalt">
								<?php echo $this->layout()->content; ?>
						</div>	
						<div class = "clear"></div>
						<div style=(font:bold;)></div>
				</div>
				<div id = "fusszeile">
						<?php echo $this->render('_layout/fusszeile.phtml')?>
				</div>
		</div>
	</body>
</html>
