<?php 
/*****************************************************************************
 * 											 								**
 * Allgemeine Infos:														**
 * Höhe: dynamisch (je nach geladenen Menüpunkten)							**
 * Breite: 150px (kann jedoch noch abweichen)								**
 * 																			**
 *****************************************************************************/
?>

<ul class="topnav">
	<li><a href="#">Artikel bearbeiten/löschen</a>
		<ul>
			 <li class="#"><a href="#">W&auml;rmetauscher</a>
				 <ul>
						<li><a href="#">Gel&ouml;tet</a></li>
						<li><a href="#">Geschraubt</a></li>
						<li><a href="#">Rohrb&uuml;ndel</a></li>
				 </ul>
			</li>
			 <li><a href="#">Pufferspeicher</a>
				 <ul>
						<li><a href="#">VVX</a></li>
						<li><a href="#">LAS</a></li>
				 </ul>
			</li>
			 <li><a href="#">Wassererw&auml;rmer</a>
 				<ul>
					<li><a href="#">SHI/SHE</a></li>
					<li><a href="#">VVI</a></li>
					<li><a href="#">VVE</a></li>
				</ul>
			</li>
			 <li><a href="#">Ladesysteme</a></li>
			 <li><a href="#">Durchlauferhitzer</a></li>
		</ul>
	</li>
	<li><a href="#">Artikel hinzufügen</a>
	<li><a href="#">Angebote bearbeiten</a>
</ul>