<?php 
/*****************************************************************************
 * 											 								**
 * Allgemeine Infos:														**
 * Höhe: dynamisch (je nach geladenen Menüpunkten)							**
 * Breite: 150px (kann jedoch noch abweichen)								**
 * 																			**
 *****************************************************************************/
?>

<ul class="topnav">
	<li><a href="#" >Artikel bearbeiten</a>
		<ul>
		<li><a href="/Admin/changewaermetauscher">W&auml;rmetauscher</a></li>
		<li><a href="/Admin/changewasserwärmer">Pufferspeicher</a></li>
		<li><a href="#">Wassererw&auml;rmer</a></li>
		</ul></li>
	<li><a href="#">Artikel hinzufügen</a>
		<ul>
			<li><a href="/Waermetauscher/hinzufuegen">gelötete Wärmetauscher</a></li>
			<li><a href="/Pufferspeicher/hinzufuegen">Pufferspeicher</a></li>
			<li><a href="/Wassererwärmer/hinzufuegen">Wassererwärmer</a></li>
		</ul></li>
	<li><a href="#">Angebote bearbeiten</a></li>
</ul>