<?php 
/*****************************************************************************
 * 											 								**
 * Allgemeine Infos:														**
 * Höhe: dynamisch (je nach geladenen Menüpunkten)							**
 * Breite: 150px (kann jedoch noch abweichen)								**
 * 																			**
 *****************************************************************************/
?>

<ul class="topnav">
	<li><a href="#" >Artikel bearbeiten</a>
		<ul>
		<li><a href="/Admin/showwaermetauscher">W&auml;rmetauscher</a></li>
		<li><a href="/Admin/showpufferspeicher">Pufferspeicher</a></li>
		</ul></li>
	<li><a href="#">Artikel hinzufügen</a>
		<ul>
			<li><a href="/Waermetauscher/hinzufuegen">gelötete Wärmetauscher</a></li>
			<li><a href="/Pufferspeicher/hinzufuegen">Pufferspeicher</a></li>
		</ul></li>
	<li><a href="#">Angebote bearbeiten</a></li>
	<li><a href="#">Attribute bearbeiten</a>
		<ul>
		<li><a href="#">Wärmetauscher</a>
			<ul>
			<li><a href="/Admin/anschluessebearbeiten">Anschlüsse</a></li>
			<li><a href="/Admin/einsatzgebietebearbeiten">Einsatzgebiete</a></li>
			<li><a href="/Admin/stutzenmaterialbearbeiten">Stutzenmaterial</a></li>
			</li></ul>
		<li><a href="#">Pufferspeicher</a>
			<ul>
			<li><a href="/Admin/einsatzgebietepsbearbeiten">Einsatzgebiete</a></li>
			</ul></li>
		</ul></li>
		
</ul>