<?php
/*****************************************************************************
 * 											 								**
 * Allgemeine Infos:														**
 * Höhe: dynamisch (je nach geladenen Menüpunkten)							**
 * Breite: 150px (kann jedoch noch abweichen)								**
 * 																			**
 *****************************************************************************/
?>

<ul class="topnav">
	<li><a href="#">Artikel hinzufügen</a>
		<ul>
			<li><a href="/waermetauscher/hinzufuegen">Wärmetauscher</a></li>
			
			
			<li><a href="/pufferspeicher/hinzufuegen">Pufferspeicher</a></li>
		</ul></li>
	<li><a href="#">Artikel bearbeiten</a>
		<ul>
			<li><a href="/admin/showwaermetauscher">W&auml;rmetauscher</a></li>
			<li><a href="/admin/showpufferspeicher">Pufferspeicher</a></li>
		</ul></li>


	<li><a href="#">Attribute bearbeiten</a>
		<ul>
			<li><a href="#">Wärmetauscher</a>
				<ul>
					<li><a href="/admin/anschluessebearbeiten">Anschlüsse</a></li>
					<li><a href="/admin/einsatzgebietebearbeiten">Einsatzgebiete</a></li>
					<li><a href="/admin/stutzenmaterialbearbeiten">Stutzenmaterial</a></li></li>
		</ul>
	
	<li><a href="#">Pufferspeicher</a>
		<ul>
			<li><a href="/admin/einsatzgebietepsbearbeiten">Einsatzgebiete</a></li>
		</ul></li>
</ul>
</li>
<li><a href="/admin/showangebote">Angebote bearbeiten</a></li>

</ul>