<?php 
/*****************************************************************************
 * 											 								**
 * Allgemeine Infos:														**
 * Höhe: dynamisch (je nach geladenen Menüpunkten)							**
 * Breite: 150px (kann jedoch noch abweichen)								**
 * 																			**
 *****************************************************************************/
?>

<ul class="topnav">
	<li><a href="#" >Artikel bearbeiten</a>
		<ul>
		<li><a href="#">W&auml;rmetauscher</a></li>
		<li><a href="#">Pufferspeicher</a></li>
		<li><a href="#">Wassererw&auml;rmer</a></li>
				<li><a href="#">VVI</a>
					<ul>
						<li><a href="/Wassererwaermer/vvi/artikel/vvi150">VVI 150</a>
						<li><a href="/Wassererwaermer/vvi/artikel/vvi400">VVI 400</a>
						<li><a href="/Wassererwaermer/vvi/artikel/vvi1000">VVI 1000</a>
					</ul></li>
				<li><a href="#">VVE</a>
					<ul>
						<li><a href="/Wassererwaermer/vve/artikel/vve500">VVE 500</a>
						<li><a href="/Wassererwaermer/vve/artikel/vve850">VVE 850</a>
						<li><a href="/Wassererwaermer/vve/artikel/vve1000">VVE 1000</a>
					</ul></li>
			</ul>
		</li>
		<li><a href="#">Ladesysteme</a></li>
		<li><a href="#">Durchlauferhitzer</a></li>
	</ul>
	</li>
		
	<li><a href="#">Artikel hinzufügen</a>
		<ul>
			<li><a href="/Waermetauscher/hinzufuegen">gelötete Wärmetauscher</a></li>
			<li><a href="/Pufferspeicher/hinzufuegen">Pufferspeicher</a></li>
			<li><a href="/Wassererwärmer/hinzufuegen">Wassererwärmer</a></li>
		</ul></li>
	<li><a href="#">Angebote bearbeiten</a></li>
</ul>