<?php 
/*****************************************************************************
 * 											 								**
 * Allgemeine Infos:														**
 * Höhe: dynamisch (je nach geladenen Menüpunkten)							**
 * Breite: 150px (kann jedoch noch abweichen)								**
 * 																			**
 *****************************************************************************/
?>

<ul class="topnav">
	<li><a href="#" >Artikel bearbeiten</a>
		<ul>
		<li><a href="#">W&auml;rmetauscher</a>
			 <ul>
				<li><a href="/Waermetauscher/index">Gel&ouml;tet</a>
					<ul>
						<li><a href="/Admin/changeWaermetauscher/artikel/bhd21">BHD 21</a></li>
						<li><a href="/Admin/changeWaermetauscher/artikel/bhd30">BHD 30</a></li>
					</ul></li>
				<li><a href="/Waermetauscher/geschraubt">Geschraubt</a></li>
				<li><a href="#">Rohrb&uuml;ndel</a></li>
			 </ul>
		</li>
		<li><a href="#">Pufferspeicher</a>
			 <ul>
				<li><a href="#">VVX</a>
					<ul>
						<li><a href="/Pufferspeicher/vvx/artikel/vvx200">VVX 200</a>
					</ul></li>
				<li><a href="#">LAS</a> 	
					<ul>
						<li><a href="/Pufferspeicher/las/artikel/las150">LAS 150</a>
						<li><a href="/Pufferspeicher/las/artikel/las500">LAS 500</a>
						<li><a href="/Pufferspeicher/las/artikel/las1000">LAS 1000</a>
					</ul></li>
			 </ul>
		</li>
		<li><a href="#">Wassererw&auml;rmer</a>
			<ul>
				<li><a href="#">SHI/SHE</a>
					<ul>
						<li><a href="/Wassererwaermer/shi/artikel/shi150">SHI 150</a>
						<li><a href="/Wassererwaermer/shi/artikel/shi750">SHI 750</a>
						<li><a href="/Wassererwaermer/shi/artikel/shi2000">SHI 2000</a>
					</ul></li>
				<li><a href="#">VVI</a>
					<ul>
						<li><a href="/Wassererwaermer/vvi/artikel/vvi150">VVI 150</a>
						<li><a href="/Wassererwaermer/vvi/artikel/vvi400">VVI 400</a>
						<li><a href="/Wassererwaermer/vvi/artikel/vvi1000">VVI 1000</a>
					</ul></li>
				<li><a href="#">VVE</a>
					<ul>
						<li><a href="/Wassererwaermer/vve/artikel/vve500">VVE 500</a>
						<li><a href="/Wassererwaermer/vve/artikel/vve850">VVE 850</a>
						<li><a href="/Wassererwaermer/vve/artikel/vve1000">VVE 1000</a>
					</ul></li>
			</ul>
		</li>
		<li><a href="#">Ladesysteme</a></li>
		<li><a href="#">Durchlauferhitzer</a></li>
	</ul>
	</li>
		
	<li><a href="#">Artikel hinzufügen</a>
		<ul>
			<li><a href="/Waermetauscher/hinzufuegen">gelötete Wärmetauscher</a></li>
			<li><a href="/Pufferspeicher/hinzufuegen">Pufferspeicher</a></li>
			<li><a href="/Wassererwärmer/hinzufuegen">Wassererwärmer</a></li>
		</ul></li>
	<li><a href="#">Angebote bearbeiten</a></li>
</ul>