<?php 
/*****************************************************************************
 * 											 								**
 * Allgemeine Infos:														**
 * Höhe: 150px 																**
 * Breite: dynamisch (848px jedoch nicht übersteigen, für 1024 Auflösung)	**
 * 																			**
 *****************************************************************************/
?>
<div id ="bannerImageWiederholung"></div>
<div id = "bannerImage">
	<div id = "account"><?php echo $this->render('_layout/account.phtml');?></div>
</div>

