<?php 
/*****************************************************************************
 * 											 								**
 * Allgemeine Infos:													??	**
 * Höhe: 150px 															??	**
 * Breite: dynamisch (848px jedoch nicht übersteigen, für 1024 Auflösung??)	**
 * 																			**
 *****************************************************************************/
?>
<ul id="footer">
	<li><a href="#" >&Uuml;ber Uns</a></li>
	<li><a href="/startseite/kontakt" >Kontakt</a></li>
	<li><a href="/startseite/agb" >AGB </a></li>
	<li><a href="/startseite/datenschutz" >Datenschutz</a></li>
	<li><a href="#" >Impressum</a></li>
</ul>