<?php 
/*****************************************************************************
 * 											 								**
 * Allgemeine Infos:														**
 * Höhe: dynamisch (je nach geladenen Menüpunkten)							**
 * Breite: 150px (kann jedoch noch abweichen)								**
 * 																			**
 *****************************************************************************/
?>
<ul class="topnav">
	<li><a href="#">W&auml;rmetauscher</a>
		 <ul>
			<li><a href="/Waermetauscher/index">Gel&ouml;tet</a>
				<ul>
					<li><a href="/Waermetauscher/index">Produktberater</a></li>
					<?php //Menü dynamisch anhand der DB füllen
					$db_mapper = new Application_Model_WaermetauscherMapper ();
					$data_list = $db_mapper->getModelListe();
					foreach ( $data_list as $articlename )
					echo '<li><a href="/Waermetauscher/geloetet/artikel/'.$articlename.'">'.$articlename.'</a></li>';	
					?>			
				</ul>
			</li>
			<li><a href="/Waermetauscher/geschraubt">Geschraubt</a></li>
			<li><a href="/Waermetauscher/rohrbuendel">Rohrb&uuml;ndel</a></li>
		 </ul>
	</li>
	<li><a href="#">Pufferspeicher</a>
		<ul>
			<li><a href="/Pufferspeicher/index">Produktberater</a></li>
			<li><a href="#">VVX 200</a></li>
			<li><a href="#">VVX 300</a></li>
			<li><a href="#">VVX 400</a></li>
			<li><a href="#">LAS 500</a></li>
			<li><a href="#">LAS 1000</a></li>
		</ul>
	</li>
	<li><a href="#">Ladesysteme</a></li>
	<li><a href="#">Durchlauferhitzer</a></li>
</ul>