<?php
/*****************************************************************************
 * 											 								**
 * Allgemeine Infos:														**
 * Höhe: dynamisch (je nach geladenen Menüpunkten)							**
 * Breite: 150px (kann jedoch noch abweichen)								**
 * 																			**
 *****************************************************************************/
?>
<ul class="topnav">
	<li><a href="#">W&auml;rmetauscher</a>
		<ul>
			<li><a href="/waermetauscher/index">Gel&ouml;tet</a>
				<ul>
					<li><a href="/waermetauscher/index">Produktberater</a></li>
					<?php 
// Menü dynamisch anhand der DB füllen
					$wt_mapper = new Application_Model_WaermetauscherMapper ();
					$wt_list = $wt_mapper->getModelListe ();
					if (is_null ( $wt_list )) {
						echo '<li>:( Error in Reading Database</li>';
					}
					if (! is_null ( $wt_list )) {
						foreach ( $wt_list as $articlename )
							echo '<li><a href="/waermetauscher/geloetet/artikel/' . $articlename . '">' . $articlename . '</a></li>';
					}
					?>			
				</ul></li>
			<li><a href="/waermetauscher/geschraubt">Geschraubt</a></li>
			<li><a href="/waermetauscher/rohrbuendel">Rohrb&uuml;ndel</a></li>
		</ul></li>
	<li><a href="#">Pufferspeicher</a>
		<ul>
			<li><a href="/pufferspeicher/index">Produktberater</a></li>
			<?php 
// Menü dynamisch anhand der DB füllen
			$ps_mapper = new Application_Model_PufferspeicherMapper ();
			$ps_list = $ps_mapper->getModelListe ();
			if (is_null ( $ps_list )) {
				echo '<li><a>:( Error </a></li>';
				echo '<li><a>in Reading Database</a></li>';
			}
			if (! is_null ( $ps_list )) {
				foreach ( $ps_list as $articlename )
					echo '<li><a href="/pufferspeicher/anzeigen/artikel/' . $articlename . '">' . $articlename . '</a></li>';
			}
			?>
		</ul></li>
	
</ul>