<div id="view-content">
		
	<?php
	// TODO Ausnahmen abfangen! ->schlumpfhandling -.-
	$data_object = $this->dbdata;
	if($this->dbdata === null){
		if ( isset($this->message))
			echo $this->message;
		else 
		echo 'Artikel konnte nicht gefunden werden';
		if (isset ( $_SERVER ['HTTP_REFERER'] )) {
			$this->view->link = $_SERVER ['HTTP_REFERER'];
		} else {
			$this->view->link = '/wassererwaermer';
		}
	}

	// Artikeldaten anordnen und anzeigen
	
	$art_model = $data_object->getModel ();
	$art_pressure = $data_object->getBetriebsDruck ();
	$art_temp = $data_object->getTemperatur ();
	$art_height = $data_object->getHoehe ();
	$art_width = $data_object->getBreite ();
	$art_material = $data_object->getStutzenmaterial ();
	$art_loc = $data_object->getWaermetauscherEinsatzgebiet ();
	$art_conn = $data_object->getWaermetauscherAnschluss ();
	$art_types = $data_object->getWaermetauscherUnterkategorie ();
	$art_nr = $data_object->getArtikelnummer();
	
	echo '<br>';
	echo '<div class="static_text2"><h1>Wärmetauscher ' . $art_model . '</h1></div>';
	
	echo '<br>';
	// TODO funzt noch ned
	echo '<div class="bild"><img src="/_files/images/waermetauscher/geloetet/'.$art_model.'.png" alt="'.$art_model.'" id ="bilder"></div>';
	
	echo '<div class="daten">';
		echo '<div class="grunddaten">';
			echo '<h2>Grunddaten:</h2>';
			echo '<br>';
			echo '<h3>Brenntemperatur:</h3>';
			echo $art_temp . '°C';
			echo '<h3>Betriebsdruck:</h3>';
			echo $art_pressure . ' bar';
			echo '<br>';
			echo '<h3>Abmessungen:</h3>';
			echo '<b>Maximale Höhe: </b>' . $art_height . ' mm<br>';
			echo '<b>Maximale Breite: </b>' . $art_width . ' mm';
		echo '</div>';
		echo '<div class="grunddaten">';
			echo '<br><br>';
			echo '<h3>Stutzenmaterial:</h3>';
			echo $art_material;
			echo '<br>';
			if (!is_array ( $art_loc )) {
				echo '<h3>Einsatzgebiet:</h3>';
				echo $art_loc;
			} else {
				echo '<h3>Einsatzgebiete:</h3>';
				foreach ( $art_loc as $each )
					echo $each->getEinsatzgebiet();
			}
			echo '<br>';
			if ( count($art_conn) >1 ) {
				echo '<h3>Anschl&uuml;sse:</h3>';
				foreach ( $art_conn as $each )
					echo $each->getAnschluss().' | ';
			} else {
				echo '<h3>Anschluss:</h3>';
				echo $art_conn[0]->getAnschluss();
				
			}
		echo '</div>';
		echo '<br><br>';
	echo '</div>';
	echo '<div class="daten">';
		echo '<br>';
		echo '<h2>Auslegungsmöglichkeiten:</h2>';
		
		
		foreach ( $art_types as $type ) {
		echo '<div class="modelle">';
			echo '<b>Modell '.$art_model.'-'.$type->getPlatten().':</b><br>';
			echo 'Anzahl Platten: '.$type->getPlatten ();
			echo '<br>Länge: '.$type->getLaenge ().'mm';
			echo '<br>Leergewicht: '.$type->getLeergewicht ().'Kg';
			echo '<br>Fläche: '.$type->getFlaeche().'m²';
			if($type->getInhaltPrimaer() !== NULL){
			echo '<br>Primärinhalt: '.$type->getInhaltPrimaer();
			if($type->getInhaltSekundaer() !== NULL)
				echo $type->getInhaltSekundaer();
			}
			echo '<br>';
		echo '</div>';
		}
		
	echo '</div>';
	if (Zend_Auth::getInstance()->hasIdentity()){
	echo  '<br><a href="/angebot/erstellen/artikelnummer/'.$art_nr.'">Angebot über diesen Artikel einholen</a><div>';
	}
	var_dump($_SESSION);
	?>
	
</div>