<div id="view-content">
		
	<?php
	// TODO Ausnahmen abfangen! ->schlumpfhandling -.-
	$data_object = $this->dbdata;
	if($this->dbdata === null){
		$this->view->message = 'Artikel konnte nicht gefunden werden';
		if (isset ( $_SERVER ['HTTP_REFERER'] )) {
			$this->view->link = $_SERVER ['HTTP_REFERER'];
		} else {
			$this->view->link = '/wassererwaermer';
		}
	}
	
	
	// Artikeldaten anordnen und anzeigen
	
	$art_model = $data_object->getModel ();
	$art_pressure = $data_object->getBetriebsDruck ();
	$art_temp = $data_object->getTemperatur ();
	$art_height = $data_object->getHoehe ();
	$art_width = $data_object->getBreite ();
	$art_material = $data_object->getStutzenmaterial ();
	$art_loc = $data_object->getWaermetauscherEinsatzgebiet ();
	$art_conn = $data_object->getWaermetauscherAnschluss ();
	$art_types = $data_object->getWaermetauscherUnterkategorie ();
	
	echo '<br>';
	echo '<h1>Wärmetauscher ' . $art_model . '</h1>';
	echo '<br>';
	// TODO funzt noch ned
	echo '<img src="/_files/images/waermetauscher/geloetet/'.$art_model.'.png" alt="'.$art_model.'" id ="bilder">';
	echo '<h2>Grunddaten:</h2> ';
	echo '<h3>Brenntemperatur:</h3>';
	echo $art_temp . '°C';
	echo '<h3>Betriebsdruck:</h3>';
	echo $art_pressure . ' bar';
	echo '<br>';
	echo '<h3>Abmessungen:</h3>';
	echo '<b>Maximale Höhe: </b>' . $art_height . ' mm<br>';
	echo '<b>Maximale Breite: </b>' . $art_width . ' mm<br>';
	echo '<br>';
	echo '<h3>Stutzenmaterial:</h3>';
	echo $art_material;
	echo '<br>';
	if (!is_array ( $art_loc )) {
		echo '<h3>Einsatzgebiet:</h3>';
		echo $art_loc;
	} else {
		echo '<h3>Einsatzgebiete:</h3>';
		foreach ( $art_loc as $each )
			echo $each->getEinsatzgebiet();
	}
	echo '<br>';
	if (!is_array ( $art_conn )) {
		echo '<h3>Anschl&uuml;sse:</h3>';
		echo $art_conn;
	} else {
		echo '<h3>Anschluss:</h3>';
		foreach ( $art_conn as $each )
			echo $each->getAnschluss();
	}
	echo '<br><br>';
	echo '<h2>Auslegungsmöglichkeiten:</h2>';
	foreach ( $art_types as $type ) {
		
		echo '<b>Modell '.$art_model.'-'.$type->getPlatten().':</b><br>';
		echo 'Anzahl Platten: '.$type->getPlatten ();
		echo '<br>Länge: '.$type->getLaenge ().'mm';
		echo '<br>Leergewicht: '.$type->getLeergewicht ().'Kg';
		echo '<br>Fläche: '.$type->getFlaeche().'m²';
		if($type->getInhaltPrimaer() !== NULL){
		echo '<br>Primärinhalt: '.$type->getInhaltPrimaer();
		if($type->getInhaltSekundaer() !== NULL)
			echo $type->getInhaltSekundaer();
		}echo '<br><br>';
	}
	
	?>
	
</div>