<html>
<div class="static_text2"><h1>Wärmetauscher im Druckgestell</h1></div>
<div>
	<div class="static_bild">
		<img align="middle"
			src="/_files/images/waermetauscher/geschraubt/waermetauscher_geschraubt.jpg"
			alt="geschraubt" id="bilder">
	</div>
	<div class="static_text">
		<p>
			<br> <br> <br>Höchste Effektivität bei der Wärmebertragung.
			Plattenwärmetauscher mit Druckgestell sind universell einsetzbar und
			können für jeden Anwendungsfall optimal ausgelegt werden.<br> <br> <br>
		</p>
	</div>
</div>
<div style="clear: both">
	<div class="static_text">
		<br> <br> <br>
		<h2>Verarbeitung</h2>
		<p>Bei Wärmetauscher mit Druckgestell erfolgt die Medientrennung und
			damit die Wärmeübertragung durch Übertragungsplatten aus Edelstahl
			oder Titan. Die Platten sind mit Dichtungen versehen, welche einen
			Medienaustritt in die Umgebung verhindern, sowie die Strömungsführung
			in den einzelnen Kanälen zwischen den Übertragungsplatten
			sicherstellen.</p>
	</div>
	<div class="static_bild">
		<br> <img
			src="/_files/images/waermetauscher/geschraubt/plattenwaermetauscher_geschraubt.jpg"
			alt="geschraubt" id="bilder"><br><br>
	</div>

</div>
<div style="clear: both">
	<div class="static_bild">
		<img
			src="/_files/images/waermetauscher/geschraubt/waermetauscher_funktion.jpg"
			alt="geschraubt" id="bilder">
	</div>
	<div class="static_text">
		<p>
			Zwei Druckplatten, die mittels Spannbolzen zusammengezogen werden,
			fixieren die Übertragungsplatten und gewährleisten die erforderliche
			Vorspannung für die Dichtungen. An den Druckplatten befinden sich die
			Anschlussstutzen, Konsolen oder Standfüße. Bei unseren Wärmetauschern
			mit Druckgestell lassen sich die Übertragungsplatten bei Bedarf ohne
			großen Aufwand entnehmen und reinigen. Damit bieten sich diese
			Tauscher für Übertragungsaufgaben mit Medien an, bei denen
			Ablagerungen nicht sicher vermieden werden können.<br> <br> <br><br>
		</p>
	</div>
</div>
<div style="clear: both">
	<div class="static_text">
		<p>
			Im Programm sind Übertragungsplatten von 0,01 m²; bis 3 m²; je Platte
			und Wärmetauscher bis 1300 m² Heizfläche Unser Sortiment umfasst 15
			verschiedene Baureihen, die wiederum mit 5 verschiedenen
			Übertragungsplatten kombiniert werden können. Zu jeder
			Übertragungsplatte gibt es 4 verschiedene Dichtungen (Nitril,
			EPDM,EPDM (PRX), Viton) mit jeweiligen Drüken von 6 - 16 - 25 bar.<br>
			<br> <br>
		</p>
	</div>
	<div class="static_bild">
		<img
			src="/_files/images/waermetauscher/geschraubt/waermetauscher_geschraubt_skizze.jpg"
			alt="geschraubt" id="bilder">
	</div>

</div>
<div style="clear: both">
	<br> <br>
	<h1>Unterschiedliche Übertragungsplatten</h1>
	<div class="static_text">
		<p>Beispiel stumpfer Winkel</p>
		<img
			src="/_files/images/waermetauscher/geschraubt/waermetauscher_platte_stumpf.jpg"
			alt="geschraubt" id="bilder">


		<p>Platten mit stumpfen Prägewinkeln (H-Platte) erzeugen höhere
			Druckverluste und hohe Wärmebertragungskoeffizienten.</p>

	</div>
	<div class="static_text">
		<p>Beispiel spitzer Winkel</p>
		<img
			src="/_files/images/waermetauscher/geschraubt/waermetauscher_platte_spitz.jpg"
			alt="geschraubt" id="bilder">
		<p>Platten mit spitzem Prägewinkel (L-Platte) erzeugen niedrige
			Druckverluste und niedrige Wärmeübertragungskoeffizienten.</p>
		<br> <br>
	</div>
</div>
<div class="static_bild">
	<img
		src="/_files/images/waermetauscher/geschraubt/waermetauscher_platte.jpg"
		alt="geschraubt" id="bilder">
</div>
<div class="static_text">
	<h2>Plattenmaterial:</h2>
	<p>Serienmäßig: Edelstahl 1.4401/AISI 316 in 0,5 mm Stärke</p>
	<p>
		Optional: 1.4539, 254 SMO, Titan <br> Weitere Materialien auf Anfrage
	</p>

	<h2>Dichtungsmaterial:</h2>
	<p>
		Serienmäßig NBR (Nitril-Kautschuk) kleberlos<br>Optional: EPDM
		Äthylen-Propylen-Kautschuk) kleberlos <br> Optional: Viton
		(Fluor-Kautschuk) kleberlos <br> Weitere Materialien auf Anfrage
	</p>
</div>


</html>