<html>
<h1>Wärmetauscher im Druckgestell</h1>
<div>
	<div id="leftern"><img  align="middle" src="/_files/images/waermetauscher/geschraubt/waermetauscher_geschraubt.jpg" alt="geschraubt" id ="bilder"></div>
	<div id="rightern"><p>Höchste Effektivität bei der Wärmebertragung.
	Plattenwärmetauscher mit Druckgestell sind universell einsetzbar und können für jeden Anwendungsfall optimal ausgelegt werden.</p></div>
</div>

<h2>Verarbeitung</h2>
<img src="/_files/images/waermetauscher/geschraubt/plattenwaermetauscher_geschraubt.jpg" alt="geschraubt" id ="bilder">
<p>Bei Wärmetauscher mit Druckgestell erfolgt die Medientrennung und damit die Wärmeübertragung durch Übertragungsplatten aus Edelstahl oder Titan. 
Die Platten sind mit Dichtungen versehen, welche einen Medienaustritt in die Umgebung verhindern, sowie die Strömungsführung in den einzelnen Kanälen zwischen den Übertragungsplatten sicherstellen.</p> 
<img src="/_files/images/waermetauscher/geschraubt/waermetauscher_funktion.jpg" alt="geschraubt" id ="bilder">
<p>
Zwei Druckplatten, die mittels Spannbolzen zusammengezogen werden, fixieren die Übertragungsplatten und gewährleisten die erforderliche Vorspannung für die Dichtungen. An den Druckplatten befinden sich die Anschlussstutzen, Konsolen oder Standfüße.

Bei unseren Wärmetauschern mit Druckgestell lassen sich die Übertragungsplatten bei Bedarf ohne großen Aufwand entnehmen und reinigen. Damit bieten sich diese Tauscher für Übertragungsaufgaben mit Medien an, bei denen Ablagerungen nicht sicher vermieden werden können.</p>
<img src="/_files/images/waermetauscher/geschraubt/waermetauscher_geschraubt_skizze.jpg" alt="geschraubt" id ="bilder">
<p>Im Programm sind Übertragungsplatten von 0,01 m2; bis 3 m2; je Platte und Wärmetauscher bis 1300 m2 Heizfläche
Unser Sortiment umfasst 15 verschiedene Baureihen, die wiederum mit 5 verschiedenen Übertragungsplatten kombiniert werden können.
Zu jeder Übertragungsplatte gibt es 4 verschiedene Dichtungen (Nitril, EPDM,EPDM (PRX), Viton) mit jeweiligen Drüken von 6 - 16 - 25 bar.
</p>
 <h1>Unterschiedliche Übertragungsplatten</h1>
<p>Beispiel stumpfer Winkel</p>
<img src="/_files/images/waermetauscher/geschraubt/waermetauscher_platte_stumpf.jpg" alt="geschraubt" id ="bilder">
<p>Platten mit stumpfen Prägewinkeln (H-Platte) erzeugen höhere Druckverluste und hohe Wärmebertragungskoeffizienten.
</p>
<p>Beispiel spitzer Winkel</p>
<img src="/_files/images/waermetauscher/geschraubt/waermetauscher_platte_spitz.jpg" alt="geschraubt" id ="bilder">
<p> Platten mit spitzem Prägewinkel (L-Platte) erzeugen niedrige Druckverluste und niedrige Wärmeübertragungskoeffizienten.</p>
<img src="/_files/images/waermetauscher/geschraubt/waermetauscher_platte.jpg" alt="geschraubt" id ="bilder">
<h2>Plattenmaterial:</h2>
<p>Serienmäßig: Edelstahl 1.4401/AISI 316 in 0,5 mm Stärke</p>
<p>
Optional: 1.4539, 254 SMO, Titan
<br>
Weitere Materialien auf Anfrage
</p>

<h2>Dichtungsmaterial:</h2>
<p>Serienmäßig NBR (Nitril-Kautschuk) kleberlosOptional: EPDM Äthylen-Propylen-Kautschuk) kleberlos
<br>
Optional: Viton (Fluor-Kautschuk) kleberlos
<br>
Weitere Materialien auf Anfrage
</p>


</html>