<?php $this->headLink()->appendStylesheet('/_files/css/olli.css');?>
<h1>Produktberater</h1>
<?php echo $this->produktberaterWt;?>

<div id="TabelleWt">

<h1>Vorschläge</h1>
<table border="1">
  <tr>
    <th>Produktname</th>
    <th>Temperatur</th>
    <th>Einsatzgebiet</th>
    <th>Anschlüsse</th>
    <th>Höhe</th>
    <th>Breite</th>
    <th>Länge</th>
  </tr>
  <tr>
  <?php foreach($produkte as $key => $value){?>
    <td><?php $value->getID(); ?></td>
    <td><?php $value->getModel(); ?></td>
    <td><?php $value->getTemperatur(); ?></td>
    <td><?php $value->getWaermetauscherEinsatzgebiet(); ?></td>
    <td><?php $value->getgetHoehe(); ?></td>
    <td><?php $value->getBreite(); ?></td>
  <?php }?>
  </tr>
</table>
</div>


     

     

