<?php $this->headLink()->appendStylesheet('/_files/css/olli.css');?>
<h1>Produktberater</h1>
<div id="produktberaterWt">
<?php echo $this->produktberaterWt;?>
</div>
<?php if($this->showVor){
		if($this->keineVorschläge){
			echo "Es gibt im Moment leider keine passenden Produkte!";
			}else{?>
<div id="TabelleWt">

<h1>Vorschläge</h1>
<table border="1">
  <tr>
    <th>Produktname</th>
    <th>Temperatur</th>
    <th>Einsatzgebiet</th>
    <th>Anschlüsse</th>
    <th>Höhe</th>
    <th>Breite</th>
  </tr>
  <?php foreach($this->vorschläge as $value){?>
   <tr>
	<?php $url = "/waermetauscher/geloetet/artikel/" . $value->getModel();?>
    <td> <a href="<?php echo $url;?>"><?php echo $value->getModel();?></a></td> 
    <td><?php echo $value->getTemperatur(); ?></td>
    <td><?php foreach($value->getWaermetauscherEinsatzgebiet() as $gbt){
    					echo $gbt->getEinsatzgebiet();
    					} ?></td>
    <td><?php 	$i=0;
    			foreach($value->getWaermetauscherAnschluss() as $ans){
    					if($i==count($value->getWaermetauscherAnschluss())-1){
    						echo $ans->getAnschluss();
    					}else{
    						echo $ans->getAnschluss() . ", ";
    						$i++;
    					}
  					}?></td>
    <td><?php echo $value->getHoehe(); ?></td>
    <td><?php echo $value->getBreite(); ?></td>
    </tr>
  <?php }?>
  
</table>
</div>
<?php 
	}
}?>


