<html>
<h1>Wärmetauscher als Rohrbündel</h1>
<div style="clear: both">
	<div class="static_bild">
		<img
			src="/_files/images/waermetauscher/rohrbuendel/waermetauscher_rohrbuendel_1.jpg"
			alt="geloetet" id="bilder">
	</div>
	<div class="static_text">
		<br>
		<br>
		<br>
		<p>Rohrbündel-Wärmetauscher eignen sich vorwiegend für die
			Wärmeübertragung zwischen verschiedenen Flüssigkeiten und Gasen. So
			werden hervorragende Ergebnisse bei der Erwärmung, bzw. Kühlung von
			Flüssigkeiten und Gasen mittels Wasser, Thermoöl, Sattdampf usw.
			erzielt.</p>

	</div>
</div>
<div style="clear: both">
	<br>
	<div class="static_grunddaten">

		<h2>Aufbau und Wirkungsweise</h2>

		<p>Die Wärmetauscher bestehen im wesentlichen aus Gehäuse und
			Rohrbündeleinsatz. Das Gehäuse ist eine Schweisskonstruktion und
			umfasst sämtliche Anschluss-, Verbindungs- und Befestigungselemente.

			Unser Sortiment umfaßt ca. 20 verschiedene Baureihen in liegender
			oder stehender Ausführung Material in Edelstahl 1.4301, Edelstahl
			1.4401, Titan, etc.</p>
			<br>
	</div>
</div>
<div style="clear: both">
	<h3 style="color: #696969">Beispiele:</h3>
	<div class="static_bild">
		<img
			src="/_files/images/waermetauscher/rohrbuendel/rohrbuendel_waermetauscher_d11.jpg"
			alt="geloetet" id="bilder">
		<p>Stehender Rohrbündel Wärmetauscher mit fest eingeschweißtem
			Gerade-Rohrbündel</p>
	</div>
	<div class="static_bild">
	<br><br><br><br><br><br><br><br><br>
		<img
			src="/_files/images/waermetauscher/rohrbuendel/rohrbuendel_waermetauscher_w35.jpg"
			alt="geloetet" id="bilder">
		<p>Liegender Rohrbündel Wärmetauscher mit ziehbarem U-Rohrbündel.</p>
	</div>
</div>
<div style="clear: both">
	<br>
	<div class="static_grunddaten">
		<h2>Bitte beachten Sie:</h2>
		<p>
			Rohrbündel-Wärmetauscher werden hauptsächlich bei großen
			Temperaturspreizungen eingesetzt Durch die vergleichsweise großen
			Spalte zwischen den Rohren zeichnen sich diese Wärmeaustauscher durch
			einen geringen Druckverlust auch bei großen Volumenströmen oder
			hochviskosen Ölen aus. Sie sind daher besonders geeignet für
			Anwendungen im Bereich der Schmiertechnik. Da die Strömung in und um
			die Kühlwasserrohre in der Regel keine starken Turbulenzen aufweist,
			ist die Wärmeübergangszahl bei Rohrbündelwärmetauscher relativ
			gering. Entsprechend groß muß die Austauschfläche gewählt werden, um
			die gewünschte Kühlleistung zu erreichen. Dies führt oft zu sehr
			großen Kühlern von einigen Metern Länge. <b>Für kleinere und genauere
				Temperaturspreizungen empfehlen wir den Einsatz von gelöteten oder
				geschraubten Plattenwärmeübertragern</b>, mit unserer ausgereiften
			Software legen wir jeden Wärmetauscher bedarfsgerecht aus
		</p>
	</div>
</div>
</html>