<br /><br />
<div id="view-content">
	<p>View script for controller <b>Wassererwaermer</b> and script/action name <b>hinzufuegen</b></p>
</div>

<?php $this->headTitle()->append('Artikel Hinzuf&uuml;egen'); ?>

<div id="register_wrapper">
	<h3>Registrieren</h3>
	<p>Bitte füllen Sie alle Pflichtfelder aus, um einen neuen Benutzer zu registrieren.</p>
	<div id="register_container">
		<?php echo $this->form; ?>
		<small>*Pflichtfelder</small>
	</div>
</div>