<?php $this->headLink()->appendStylesheet('/_files/css/olli.css');?>
<h1>Produktberater</h1>
<?php echo $this->produktberaterWw;?>

<?php 
if($this->showVor == true){
?>
<div id="TabelleWw">

<h1>Vorschläge</h1>
<table border="1">
  <tr>
    <th>Produktname</th>
    <th>Typ</th>
    <th>Heizwendel</th>
    <th>Speicherinhalt</th>
    <th>Leergewicht</th>
    <th>AnschlussKw</th>
    <th>AnschlussWw</th>
  </tr>
  <tr>
    <td>...</td>
    <td>....</td>
    <td>...</td>
    <td>...</td>
    <td>...</td>
    <td>...</td>
    <td>...</td>
  </tr>
</table>
</div>
<?php 
}
?>

