<h1><a name="top">Allgemeine Gesch&auml;ftsbedingungen</a></h1> 
<p>
  Wir liefern nur aufgrund dieser Lieferungs- und Zahlungsbedingungen. Folgegesch&auml;fte gelten auch dann, 
  wenn nicht nochmals auf die AGB`s hingewiesen wird. Abweichende Bedingungen, auch Gesch&auml;ftsbedingungen des K&auml;ufers 
  bed&uuml;rfen der Schriftform und der schriftlichen Best&auml;tigung. 
</p>
<br>
<h3>Vertragsabschluss</h3>
<p>Angebote schriftlich, m&uuml;ndlich oder aus dem Internet sind freibleibend und unverbindlich. Bei Abschl&uuml;ssen, deren Erf&uuml;llung in mehreren Einzellieferungen erfolgt, gilt jede Lieferung gesondertes Gesch&auml;ft.</p>
<br>
<h3>Gew&auml;hrleistung</h3>
<p>Die Gew&auml;hrleistungsfrist f&uuml;r alle gekauften und gelieferten Gegenst&auml;nde und Anlagen betr&auml;gt 24 Monate ab Annahme &uuml;bergabetag. L&auml;ngere Garantiezeiten sind g&uuml;ltig, wenn der Hersteller die Zeiten in den original Papieren dokumentiert und best&auml;tigt. </p>
<br>
<h3>Preise Inland</h3>
<p>Die Preise verstehen sich in EURO ( &euro; ) ab Versandort. Die Versandart bleibt uns vorbehalten. </p>
<br>
<h3>Preise Ausland</h3>
<p>F&uuml;r Auslandslieferungen gelten die Bedingungen Inland bis zur Deutschen Grenze. Ab deutscher Grenze unfrei.</p>
<br>
<h3>Auftrags&auml;nderungen</h3>
<p> Nachtr&auml;gliche Auftrags&auml;nderungen, Mengen&auml;nderungen und Streichungen k&ouml;nnen nur anerkannt werden, wenn noch keine Kosten angefallen sind. Im anderen Falle werden dem Besteller die Kosten in Rechnung gestellt.</p> 
<br>
<h3>Lieferzeiten</h3>
<p>Liefertermine oder Lieferfristen, die verbindlich und unverbindlich vereinbart werden k&ouml;nnen, sind schriftlich anzugeben. Lieferfristen beginnen ab Vertragsabschluss. Bei Verz&ouml;gerungen der Lieferung (und Nachlieferung) behalten wir uns vor, in Teillieferungen zu liefern. Die von uns best&auml;tigte Lieferzeit ist ein voraussichtlicher Liefertermin und gilt f&uuml;r die Auslieferung ab Werk. Wir unternehmen alle angemessenen Anstrengungen mit dem Ziele rechtzeitiger Lieferung. Zum R&uuml;cktritt vom Vertrag wegen Nichteinhaltung der Lieferfrist ist der Besteller erst dann berechtigt, wenn er uns schriftlich eine angemessene Nachfrist gesetzt hat. Die Nichteinhaltung der vereinbarten Lieferzeit berechtigt den K&auml;ufer nicht zur Geltendmachung von Schadenersatzanspr&uuml;chen. Der K&auml;ufer kann sich nicht auf mangelndes Lieferinteresse berufen (&sect; 326,2 BGB).</p> 
<br>
<h3>Widerrufsrecht (FernAbsG)</h3>
<p>Entsprechend dem Fernabsatzgesetz (FernAbsG) besteht nach Erhalt der Ware ein 14-t&auml;giges Widerrufsrecht; d. h. der K&auml;ufer kann ohne Angabe von Gr&uuml;nden vom Vertrag zur&uuml;cktreten. Bereits geleistete Zahlungen werden nach R&uuml;ckerhalt der Ware erstattet.</p>
<br>
<h3>Beanstandungen und R&uuml;cksendungen</h3>
<p>Der Besteller hat die empfangene Ware unverz&uuml;glich nach Eintreffen auf Menge, Beschaffenheit und zugesicherte Eigenschaften zu untersuchen.
 Geringe Mass- oder Farbabweichungen gelten als bedingungsgem&auml;ss und berechtigen nicht zu M&auml;ngelr&uuml;gen.
 Versteckte M&auml;ngel sind innerhalb von 14 Tagen nach Feststellung sp&auml;testens aber bis zum Ablauf von 6 Monaten seit Lieferung schriftlich anzuzeigen. Will der K&auml;ufer M&auml;ngelr&uuml;ge erheben, so ist die R&uuml;ge bei offen zutage tretenden M&auml;ngel nur innerhalb einer Woche zul&auml;ssig, ansonsten ist der Verk&auml;ufer von der Mangelhaftung befreit.
 Gew&auml;hrleistungsarbeiten werden ohne Berechnung von Kosten f&uuml;r den K&auml;ufer durchgef&uuml;hrt. W&auml;hrend der gesamten Gew&auml;hrleistungszeit m&uuml;ssen die defekten Artikel vom K&auml;ufer kostenfrei an den Verk&auml;ufer oder an die Vertragswerkstatt der Hersteller geschickt werden. F&uuml;r den transportsicheren Versand ist der K&auml;ufer verantwortlich.
 Nach erfolgter Instandsetzung wird das Ger&auml;t kostenfrei an den K&auml;ufer zur&uuml;ckgeschickt.
 F&uuml;r die Fristberechnung ist der Zeitpunkt der Anlieferung und der Tag des Eingangs des R&uuml;ckschreibens massgebend. Zur Beseitigung hat der Besteller uns die nach billigendem Ermessen erforderliche Zeit und Gelegenheit zu gew&auml;hren. Sollten wir eine gestellte Nachfrist verstreichen lassen ohne den Mangel zu beheben oder Ersatz zu liefern, oder wenn Nachbesserungen bzw. Ersatzleistungen unm&ouml;glich oder von uns verweigert werden, so steht dem Besteller nach seiner Wahl das Recht zu, R&uuml;ckg&auml;ngigmachung des Vertrages (Wandlung) oder Herabsetzung des Kaufpreises (Minderung bis max. 15% des Kaufpreises) zu verlangen.
 Die Ware wird nur im unbenutztem, einwandfreiem und original verpacktem Zustand zur&uuml;ckgenommen. 
 Ware, die speziell angefertigt werden muss, ist vom Umtausch ausgeschlossen. 
 Unangek&uuml;ndigte R&uuml;cksendungen und unfreie Sendungen werden nicht angenommen und gelangen zur&uuml;ck an den Absender. Informieren Sie sich bitte vor R&uuml;cksendung schriftlich oder telefonisch nach der Anschrift des je nach Artikels zust&auml;ndigen Auslieferungslagers (der Firmensitz in Gelsenkirchen nimmt keine R&uuml;cksendungen an, da von dort nur der Vertrieb erfolgt).
 Schadensanspr&uuml;che des Bestellers aus positiver Forderungsverletzung oder aus Verletzung von Pflichten bei Vertragsverhandlungen und aus unerlaubter Handlung werden ausgeschlossen. Dies gilt nicht, soweit in F&auml;llen des Vorsatzes oder der groben Fahrl&auml;ssigkeit des Lieferers, seines gesetzlichen Vertreters oder seiner Erf&uuml;llungshilfen zwingend gehaftet wird. Diese Haftungsbegrenzung gilt f&uuml;r den Besteller entsprechend. <p>
<br>
<h3>Versand und Liefersch&auml;den</h3>
<p> Alle Sendungen reisen auf Rechnung und Gefahr des K&auml;ufers auch wenn franko geliefert wird. Die Gefahr geht auf den Besteller &uuml;ber, sobald die Ware den Betrieb oder das Herstellerlager verlassen hat. 
 Bei Liefersch&auml;den heben Sie bitte unbedingt die Verpackung mit allen Versandpapieren auf. Setzen Sie sich mit dem entsprechenden Versandunternehmen in Verbindung und lassen Sie sich den Schaden schriftlich best&auml;tigen. 
</p>
<br>
<h3>Zahlungsweise</h3>
<p>
Innerhalb 20 Tage nach Erhalt der Ware rein netto, sofern nichts anderes vereinbart wurde. Bei Auslandslieferungen, ggfls. auch Neukunden, behalten wir uns vor, die Lieferung nur gegen Vorkasse zu versenden.
 Lieferungen per Rechnung sind nur nach schriftlicher Bestellung mit kompletter Postanschrift und Telefonnummer (keine Mobilfunknummern) an unsere Firmenadresse oder per Fax - jeweils mit rechtsg&uuml;ltiger Unterschrift - m&ouml;glich.
 Die gelieferte Ware bleibt bis zur restlosen Zahlung unser Eigentum. Vorher ist Verpf&auml;ndung oder Sicherungs&uuml;bereignung untersagt und Weiterver&auml;usserung nur Wiederverk&auml;ufern im gew&ouml;hnlichen Gesch&auml;ftsgang gestattet. Etwaige Kosten aus Intervention tr&auml;gt der Besteller. Die Forderungen des Bestellers aus einer Weiterver&auml;usserung der Vorbehaltsware werden bereits jetzt zur Sicherung s&auml;mtlicher Forderungen des Lieferers aus dem Gesch&auml;ftsverh&auml;ltnis an diesen abgetreten. Bei Zahlungsverzug werden lt. geltender Rechtsprechung Zinsen und Provisionen in H&ouml;he von 5 % &uuml;ber dem jeweiligen Basiszinsatz der Deutschen Bundesbank f&auml;llig, ohne dass es einer Inverzugsetzung bedarf. 
 Bei Rechtsgesch&auml;ften, an denen kein Verbraucher beteiligt ist, betr&auml;gt der Verzugszins f&uuml;r Entgeltforderungen dagegen 8 % &uuml;ber dem Basiszinssatz (&sect; 288 Abs. 2 BGB). 
 Bei Zahlung durch eine ausl&auml;ndische Bank tr&auml;gt der Kunde die Bankgeb&uuml;hren. 
</p>
<br>
<h3>Eigentumsvorbehalt</h3>
<p>
Die Ware bleibt unser Eigentum bis zur Bezahlung s&auml;mtlicher, auch k&uuml;nftig entstehender oder bedingter Forderungen aus unserer Gesch&auml;ftsbeziehung. 
</p>
<br>
<h3>Datenschutz</h3>
<p>
Wir speichern und verwenden Ihre Daten nur f&uuml;r die Abwicklung des Vertragsverh&auml;ltnisses (gegebenenfalls mit verbundenen Unternehmen zur Kreditpr&uuml;fung) und im Rahmen der Zusendung. Selbstverst&auml;ndlich werden Ihre Angaben vertraulich behandelt. 
</p>
<br>
<h3>Teilnichtigkeit</h3>
<p>
Falls eine Bestimmung dieser Lieferungs- und Zahlungsbedingungen oder eines ihnen unterliegenden Kaufvertrages (Auftrages) ung&uuml;ltig ist oder wird, so ber&uuml;hrt dies im Zweifel nicht die G&uuml;ltigkeit der &uuml;brigen Bestimmungen. Anstelle der ung&uuml;ltigen Bestimmung tritt vielmehr eine g&uuml;ltige, welche dem Sinn und Zweck der ung&uuml;ltigen am n&auml;chsten kommt. 
</p>
<br>
<h3>Gerichtsstand</h3>
<p>
F&uuml;r Vertr&auml;ge mit Kaufleuten, juristischen Personen des &ouml;ffentlichen Rechts und &ouml;ffentlich-rechtlichen Sonderverm&ouml;gen wird als Erf&uuml;llungsort f&uuml;r Lieferung und Zahlung sowie als Gerichtsstand Gelsenkirchen vereinbart; wir sind jedoch berechtigt, auch am Ort des Sitzes oder einer Niederlassung des K&auml;ufers zu klagen
</p>
<div align="right"><a href="#top">nach oben</a></div>
