<h1><a name="top">ThermInox W&auml;rmetechnik:</a></h1>
<br>
<p>Stand: 16.12.2013</p> 
 
<br>
<h3>Haftungsausschuss</h3>
<p>Trotz gr&ouml;&szlig;ter Sorgfalt bei der Erstellung unserer Seiten k&ouml;nnen wir f&uuml;r die Richtigkeit, Aktualit&auml;t und Vollst&auml;ndigkeit keine Garantie &uuml;bernehmen
Nach &sect;&sect; 8 bis 10 TMG sind wir als Diensteanbieter nicht verpflichtet, &uuml;bermittelte oder gespeicherte fremde Informationen zu &uuml;berwachen oder nach Umst&auml;nden zu forschen, die auf eine rechtswidrige T&auml;tigkeit hinweisen. 
Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte selbstverst&auml;ndlich umgehend entfernen.</p>
<br>
<h3>Datenschutz:</h3>
<p>Unsere Homepage verwendet Google Analytics. Durch den Besuch der Website k&ouml;nnen Informationen &uuml;ber den Zugriff (Datum, Uhrzeit, betrachtete Seite) gespeichert werden. Diese Daten werden ausschlie&szlig;lich zu statistischen Zwecken ausgewertet. Eine Weitergabe an Dritte, zu kommerziellen oder nichtkommerziellen Zwecken, findet nicht statt.
Auf dieser Internetseite werden Cookies eingesetzt. Dies sind kleine Dateien mit Konfigurationsinformationen um spezielle Benutzerfunktionen zu realisieren. &uuml;ber die Cookies werden keine personenbezogenen Daten erfasst. S&auml;mtliche Funktionen der Website sind auch ohne Cookies nutzbar, einige benutzerdefinierte Eigenschaften und Einstellungen sind dann allerdings nicht oder nur teilweise verf&uuml;gbar.
</p>
<br>
<h3>Kundendaten</h3>
<p>Kundendaten werden ausschlie&szlig;lich f&uuml;r die Abwicklung der Bestellung erfragt, gespeichert und verwendet. Grundlage hierf&uuml;r sind die einschl&auml;gigen Datenschutzbestimmungen, insbesondere des Bundesdatenschutzgesetzes (BDSG) und des Teledienstedatenschutzgesetzes (TDDSG).
Um Ihre Bestellung oder Anfrage abwickeln oder ausliefern zu k&ouml;nnen, geben wir Ihre Daten nur an den jeweils mit der Auslieferung beauftragten Lieferdienst weiter. ThermInox stellt Ihre pers&ouml;nlichen Daten nicht anderen zur Verf&uuml;gung, d.h. in keinem Fall werden wir Ihre Daten verkaufen oder vermieten. 
An verschiedenen Stellen ist es Ihnen m&ouml;glich, uns freiwillig personenbezogene Daten zu &uuml;bermitteln. Diese Daten werden von uns nur mit Ihrer Einwilligung zu diesem Zwecke oder zur Abwicklung von Vertr&auml;gen und der technischen Administration erhoben und gespeichert.
</p>
<br>
<h3>Uhrheberrecht</h3>
<p>Unsere Inhalte unterliegen dem deutschen Urheberrecht. Eine Bearbeitung, Vervielf&auml;ltigung oder jegliche Art der Verwertung au&szlig;erhalb der Grenzen des Urheberrechtes bed&uuml;rfen unserer schriftlichen Zustimmung 
Downloads und Kopien dieser Seite sind nur f&uuml;r den privaten, aber nicht kommerziellen Gebrauch gestattet. 
</p>
<br>
<h3>Haftung externer Links</h3>
<p>Unsere Seiten enthalten ggfls.Links zu externen Websites, auf deren Inhalte wir keinen Einfluss haben. Eine Gew&auml;hrleistung dieser Links ist daher nicht m&ouml;glich
Links zu externen Seiten werden nur bei Erstellung auf m&ouml;gliche rechtliche Verst&ouml;&szlig;e &uuml;berpr&uuml;ft. Eine permanente Kontrolle der Links auf Rechtsverst&ouml;&szlig;e ist nicht zumutbar
Sollten konkrete Anhaltspunkte einer Rechtsverletzung bestehen, werden wir entsprechende Links umgehend entfernen.
</p>
<br>
<h3>Sicherheitshinweis</h3>
<p>Wir sind bem&uuml;ht, Ihre personenbezogenen Daten so zu verarbeiten, dass sie f&uuml;r Dritte nicht zug&auml;nglich sind. Wir weisen aber darauf hin, dass die &uuml;bertragung Ihrer Daten &uuml;ber das Internet im Wesentlichen weitgehend ungesichert erfolgt und somit die Datensicherheit von uns nicht gew&auml;hrleistet werden kann. Bei vertraulichen Informationen empfehlen wir Ihnen den Postweg.
</p>
<br>
<h3>Widerrufsrecht</h3>
<p>Sollten Sie im Nachhinein Einw&auml;nde gegen die Speicherung, Verarbeitung oder Nutzung Ihrer Daten haben, k&ouml;nnen Sie Ihre Einwilligung zur Datenspeicherung jederzeit ohne Angabe von Gr&uuml;nden widerrufen, bzw. die Berichtigung, Sperrung oder L&ouml;schung Ihrer personenbezogenen Daten verlangen.
</p>
<div align="right"><a href="#top">nach oben</a></div>