<p>ThermInox Wärmetechnik:</p>
<p>Middelicher Str. 8</p>
<p>45891 Gelsenkirchen</p>
<br>
<p>Büro, Lager, Warenausgabe:</p>
<p>Reginaweg 7</p>
<p>45892 Gelsenkirchen</p>
<br>
<br>
<h4>Telefon</h4>
<br>
<p>0209 1776218</p>
<p>Fax</p>
<br>
<p>0209 1776217</p>
<p>Fax / Technik</p>
<br>	
<p>0209  778464 </p>
<br>
<p>Öffnungszeiten:</p>
<p>Mo. - Do.	</p>
<p>8:00 - 16:30</p>
<br>
<p>Freitag</p>
<p>8:00 - 13:30</p>
<br>
<h4>Internet:</h4>
<br>
<p>therminox.local</p>
<p>test.therminox@gmail.com</p>
<br>
<h4>Copyright:</h4>
<br>
<h4>Copyright © by therminox.local</h4>
<br>
<h4>Alle Rechte vorbehalten.</h4>
<br>
<p>Verbreitung nur mit schriftlicher Genehmigung von therminox.local.</p>
<br>
<p>Dies gilt auch für die Aufnahme in elektronische Datenbanken und Vervielfältigung auf CD-ROM.</p>
<br>
<p>Texte und Bilder sind urheberrechtlich geschützt und dürfen weder reproduziert noch wiederverwendet oder für gewerbliche Zwecke verwendet werden.</p>
<br>
<h4>Haftungshinweis:</h4>
<p>Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.</p> 