<div id="view-content">
	<?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->Begriff) ?></dt>
    <dd><?php echo $this->escape($entry->ErklaerungID) ?></dd>
    <?php endforeach ?>
</div>
	<?php $this->headLink()->appendStylesheet('/css/olli.css');?>
	<div align="center">
	<h1>ThermInox Wärmetechnik</h1>
		<h2>Eines der größten Wärmetauscher und Edelstahlbehälter Sortimente Deutschlands.</h2>
			<br/><br/>
			</div>
			<p>Therminox ist Ihr Lieferant für Komponenten und Systeme zur Trinkwassererwärmung, für
			Wärmetauscher und Edelstahlbehälter, für Speicherladesysteme und Fernwärmeübergabestationen
			zum Einsatz in Wohngebäuden, Gewerbe und Industrie.</p>
			<br/><br/>
		<h2>Produktübersicht</h2>
			<br/>
			<h3>Wärmetauscher</h3>
				<img src="/_files/images/geloetet.png" alt="geloetet" id ="bilder">
				<p>In einem Wärmetauscher wird die Temperatur eines Mediums auf ein anderes Medium übertragen.
				 Wärmetauscher werden eingesetzt in der Trinkwassererwärmung, Heiztechnik, in Kühlanlagen und 
				 in vielen anderen Prozessen.</p>
				<br/><br/>
				<br/><br/>
				<br/><br/>
				<br/><br/>
			<h3>Pufferspeicher</h3>
				<img src="/_files/images/vvx.png" alt="VVX" id="bilder">
				<p>Unter einem Puffer versteht man in einer Heizungsanlage einen Wärmespeicher, der mit Wasser 
				befüllt ist. Er dient dazu, Differenzen zwischen der erzeugten und der verbrauchten Wärmeleistung
				auszugleichen. Auf diese Weise können die Systemkomponenten zur Wärmeerzeugung weitgehend 
				unabhängig vom Verbrauch betrieben werden. Hierdurch ergibt sich für viele Wärmeerzeuger ein 
				besseres Betriebsverhalten und ein besserer Wirkungsgrad.</p>
				<br/>
				<br/><br/>
				<br/><br/>
				<br/><br/>
			<h3>Wassererwärmer</h3>
				<img src="/_files/images/vve.png" alt="VVE" id="bilder">
				<p>In den meisten Heizungsanlagen wird heute die Trinkwassererwärmung über 
				Speicher-Wassererwärmer realisiert. Da das Speicherverhalten dem praktischen Warmwasserverbrauch 
				mit den über den Tag verteilt unregelmäßigen Zapfungen entgegenkommt, haben sich 
				Speicher-Wassererwärmer bei kleinen wie großen Warmwasserbedarfen durchgesetzt. Sie sind zu 
				finden im Einfamilienhaus bis hin zu großen Hotels oder Schwimmbädern.</p>
				<br/>
				<br/><br/>
				<br/><br/>
				<br/><br/>
			<h3>Ladesysteme</h3>
				<img src="/_files/images/Ladesysteme.png" alt="Ladesysteme" id="bilder">
				<p>Die Speicherladesysteme dienen der bedarfsgerechten Warmwasserbereitung mittels Wasserspeicher
				und externem Wärmetauscher. Durch die genaue Abstimmung der Übertragungsleistung an die 
				verfügbare Heizleistung kann das Speichervolumen klein gehalten werden.</p>
				<br/>
				<br/><br/>
				<br/><br/>
				<br/><br/>
			<h3>Durchlauferhitzer</h3>
				<img src="/_files/images/Durchlauferhitzer.png" alt="Durchlauferhitzer" id="bilder">
				<p>Die Durchlaufwassererwärmer dienen der bedarfsgerechten Warmwasserbereitung aus Nah- bzw. Fernwärme. Sie zeichnen sich durch geringe Wärmeverluste und einen hohen Wirkungsgrad aus.</p>
				<br/>
				<br/><br/>
<!-- Produktberater  -->
<h3>Produktberater</h3>
<?php $this->headTitle()->append('Productadviser'); ?>
<?php $this->headLink()->appendStylesheet('/css/produktadviser.css');?>
<p> Speicherkapazität:
<input type="range" min="0" max="50" value="0" step="5" onchange="showValue(this.value)" />
<span id="range">0</span>
<script type="text/javascript">
function showValue(newValue)
{
	document.getElementById("range").innerHTML=newValue;
}
</script>
</p>
<p>Leergewicht: 
<input type="range" min="0" max="50" value="0" step="5" onchange="showValue(this.value)" />
<span id="range">0</span>
<script type="text/javascript">
function showValue(newValue)
{
	document.getElementById("range").innerHTML=newValue;
}
</script>
</p>
<p> Eigenschaft: 


<!-- Slider JQuery -->
<script>
$(function() {
$( "#slider-speicherkapazität" ).slider({
range: true,
min: 0,
max: 500,
values: [ 75, 300 ],
slide: function( event, ui ) {
$( "#amount1" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
}
});
$( "#amount1" ).val( "$" + $( "#slider-speicherkapazität" ).slider( "values", 0 ) +
" - $" + $( "#slider-speicherkapazität" ).slider( "values", 1 ) );
});
</script>
<p>
<label for="amount1">Speicherkapazität:</label>
<input type="text" id="amount1" style="border:0; color:#f6931f; font-weight:bold;">
</p>
<div id="slider-speicherkapazität"></div>

<!--  nochmal :D -->
<script>
$(function() {
$( "#slider-leergewicht" ).slider({
range: true,
min: 0,
max: 500,
values: [ 75, 300 ],
slide: function( event, ui ) {
$( "#amount2" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
}
});
$( "#amount2" ).val( "$" + $( "#slider-leergewicht" ).slider( "values", 0 ) +
" - $" + $( "#slider-leergewicht" ).slider( "values", 1 ) );
});
</script>
<p>
<label for="amount2">Leergewicht:</label>
<input type="text" id="amount2" style="border:0; color:#f6931f; font-weight:bold;">
</p>
<div id="slider-leergewicht"></div>
