<div id="wtunterkategorienbearbeiten">
<?php $this->headLink()->appendStylesheet('/_files/css/form.css');?>
<h1>Wärmetauscher Unterkategorien bearbeiten</h1>
<?php 
echo $this->wtunterkategorienbearbeiten; 

if($this->showMessageUn === true){
?>
<div id="geändertUk">
<p>Wärmetauscher Unterkategorie wurde erfolgreich geändert</p>
</div>
<?php }?>
<?php if($this->showMessageUn === false){?>
<p>Fehler beim Ändern der Unterkategorie!"</p>
<?php }?>
</div>