<div id="wtbearbeiten">
<?php $this->headLink()->appendStylesheet('/_files/css/olli.css');?>
<h1>Wärmetauscher bearbeiten</h1>
<?php 
echo $this->wtbearbeiten; 

if($this->showMessage == true){
?>
<div id="geändert">
<p>Wärmetauscher wurde erfolgreich geändert</p>
<?php }else{?>
<p>Fehler beim ändern des Artikels!</p>
</div>
<?php }?>
</div>
<?php if($this->showUnterkategorien == true){?>
	<h1>Unterkategorien bearbeiten</h1>
	<table border="1">
 	 <tr>
    	<th>Unterkategorie</th>
    	<th>Anzahl Platten</th>
    	<th>Länge</th>
    	<th>Leergewicht</th>
    	<th>Fläche</th>
   	 	<th></th>
    	<th></th>
  	</tr>
	<?php $i = 0;
		  foreach($this->kategorien as $value){?>
		<tr>
			<td> Modell-<?php echo $value->getPlatten();?></td>
			<td><?php echo $value->getPlatten();?></td>
			<td><?php echo $value->getLaenge();?></td>
			<td><?php echo $value->getLeergewicht();?></td>
			<td><?php echo $value->getFlaeche();?></td>
			<?php $urlBearbeiten = "/Admin/changewtunterkategorie/artikel/" . $this->artikel->getModel() . "?index=" . $i;?>
			<?php $i++; ?>
			<td><a href="<?php echo $urlBearbeiten;?>">bearbeiten</a></td>
			<?php $urlLoeschen = "/Admin/deletewtunterkategorie/artikel" . $this->artikel->getModel();?>
			<td><a href="<?php echo $urlLoeschen;?>">löschen</a></td>
			</tr>
<?php } ?>
</table>
<?php }?>	
