<div id="view-content">
<?php $this->headLink()->appendStylesheet('/_files/css/olli.css');?>
<h1>Pufferspeicher bearbeiten</h1>
<table border="1">
  <tr>
    <th>Produktname</th>
    <th>Einsatzgebiet</th>
    <th>Speicherinhalt</th>
    <th>Betriebsdruck</th>
    <th></th>
    <th></th>
  </tr>
  <?php 
  if(!empty($this->dbdata)){
  	if(isset($_SESSION['psnotdelete'])){
  			echo "Artikel darf nicht gelöscht werden, da noch ein Angebot dafür existiert!";
  			unset($_SESSION['psnotdelete']);
  			}
  	foreach($this->dbdata as $value){?>
   <tr>
	<td><?php echo $value->getModel(); ?></td>
    <td><?php foreach($value->getEinsatzgebiet() as $gbt){
    					echo $gbt->getEinsatzgebiet();
    					} ?></td>
    <td><?php echo $value->getSpeicherinhalt(); ?></td>
    <td><?php echo $value->getBetriebsdruck(); ?></td>
    <?php $urlBearbeiten = "/Admin/changepufferspeicher/artikel/" . $value->getModel();?>
    <td> <a href="<?php echo $urlBearbeiten;?>">bearbeiten</a></td>
    <?php $urlLoeschen = "/Admin/deletepufferspeicher/artikel/" . $value->getModel();?>
    <td> <a href="<?php echo $urlLoeschen;?>">löschen</a></td>
    </tr>
  <?php }
  	}else{
  	echo "Keine Produkte in der Datenbank!";
  	}?>
</table>
</div>
