<?php $this->headLink()->appendStylesheet('/_files/css/olli.css');?>
<h1>Stutzenmaterial bearbeiten</h1>
<div id ="stutzenmaterialbearbeiten">
<?php echo $this->attributeBearbeiten;?>
</div>
<?php if(isset($_SESSION['stutzenmaterialNotDeleted'])){
			echo "Stutzenmaterial darf nicht gelöscht werden, da mindestens ein Artikel dieses Stutzenmaterial besitzt!";
			unset($_SESSION['stutzenmaterialNotDeleted']);
			}?>
<?php if(isset($_SESSION['stutzenmaterialNotInserted'])){
			echo "Stutzenmaterial kann nicht hinzugefügt werden, da es schon existiert!";
			unset($_SESSION['stutzenmaterialNotInserted']);
			}?>